artifact_uri: /home/moabouag/far/cliniq/runs/mlflow/521018497054149178/8a4ddb426e4c4cffad10e079e1e1c7d1/artifacts
end_time: null
entry_point_name: ''
experiment_id: '521018497054149178'
lifecycle_stage: active
run_id: 8a4ddb426e4c4cffad10e079e1e1c7d1
run_name: yolo_v8x_base_1024
source_name: ''
source_type: 4
source_version: ''
start_time: 1769616608452
status: 1
tags: []
user_id: moabouag
