#!/bin/bash
# ClinIQ — point the login-node LiteLLM proxy at the GPU LLM job.
#
# Run this on the login node AFTER `sbatch slurm/llm_gpu.sbatch` reports READY.
# It reads the GPU node's endpoint (published on shared NFS by the job),
# regenerates a GPU-flavoured LiteLLM config, and restarts the proxy so the
# chatbot's fallback becomes the fast, GPU-served gpt-oss:20b.

set -euo pipefail

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
ROOT="/data/user/moabouag/far/cliniq"
ENDPOINT_FILE="$ROOT/.local/gpu_llm_endpoint.txt"
MODEL="${CLINIQ_LLM_MODEL:-gpt-oss:20b}"

if [ ! -f "$ENDPOINT_FILE" ]; then
  echo -e "${RED}✗ $ENDPOINT_FILE not found.${NC}"
  echo -e "${YELLOW}  Submit the GPU job first:  sbatch slurm/llm_gpu.sbatch${NC}"
  exit 1
fi

ENDPOINT="$(cat "$ENDPOINT_FILE")"          # e.g. lair-g5:11434
echo -e "${GREEN}GPU LLM endpoint: $ENDPOINT${NC}"

echo "Checking reachability from the login node ..."
if ! curl -s -o /dev/null --max-time 5 "http://$ENDPOINT/api/version"; then
  echo -e "${RED}✗ Cannot reach http://$ENDPOINT — is the SLURM job running (squeue -u \$USER)?${NC}"
  exit 1
fi
echo -e "${GREEN}✓ reachable${NC}"

# Generate a GPU-flavoured proxy config: same primary (jetstream), but the
# fallback now points at the GPU node and serves the stronger model.
cat > "$ROOT/llm-gateway/config.gpu.yaml" <<YAML
# AUTO-GENERATED by slurm/point_to_gpu.sh — points the fallback at the GPU node.
model_list:
  - model_name: gpt-oss-120b
    litellm_params:
      model: openai/gpt-oss-120b
      api_base: https://llm.jetstream-cloud.org/api
      api_key: os.environ/JETSTREAM_API_KEY
      timeout: 10
  - model_name: local-fallback
    litellm_params:
      model: ollama/$MODEL
      api_base: http://$ENDPOINT
      timeout: 120
router_settings:
  fallbacks:
    - gpt-oss-120b: ["local-fallback"]
  num_retries: 0
  timeout: 120
  cooldown_time: 120
litellm_settings:
  drop_params: true
YAML

echo "Restarting LiteLLM proxy with the GPU config ..."
pkill -f "litellm --config" 2>/dev/null || true
sleep 2

set -a; [ -f "$ROOT/chatbot-app/.env" ] && source "$ROOT/chatbot-app/.env"; set +a
export JETSTREAM_API_KEY="${API_KEY:-}"

nohup litellm --config "$ROOT/llm-gateway/config.gpu.yaml" --port 4000 \
  > /tmp/cliniq_litellm.log 2>&1 &
disown
sleep 5

if curl -s -o /dev/null --max-time 5 http://127.0.0.1:4000/health/liveliness; then
  echo -e "${GREEN}✓ LiteLLM proxy up on :4000, fallback -> $MODEL @ $ENDPOINT (GPU)${NC}"
  echo "Quick test:"
  curl -s http://127.0.0.1:4000/chat/completions \
    -H "Content-Type: application/json" \
    -d "{\"model\":\"gpt-oss-120b\",\"messages\":[{\"role\":\"user\",\"content\":\"hi\"}],\"max_tokens\":15}" \
    | python3 -c "import json,sys; d=json.load(sys.stdin); print('  served by:', d.get('model'))" 2>/dev/null || true
else
  echo -e "${RED}✗ proxy failed to start — see /tmp/cliniq_litellm.log${NC}"; exit 1
fi
